version: "3.8"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "8m"
    max-file: "1"

services:
  gost:
    image: mirror-docker.runflare.com/gogost/gost:3.2.6
    container_name: v2socks-gost
    logging: *default-logging
    restart: always
    command: -L socks5://:1080 -L http://:3080 -F sni://94.130.13.19:443
    ports:
      - "1080:1080"
      - "3080:3080"
    networks:
      - proxy-net

  tun2proxy:
    image: ghcr.io/tun2proxy/tun2proxy-alpine:latest
    container_name: v2socks-tun2proxy
    logging: *default-logging
    restart: always
    depends_on:
      - gost
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.default.disable_ipv6=0
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "2017:2017"
      - "20170:20170"
    extra_hosts:
      - host.docker.internal:host-gateway
    command: --proxy socks5://gost:1080 --dns-addr 1.1.1.1 --dns virtual
    # command: --proxy socks5://host.docker.internal:1080 --dns-addr 1.1.1.1 --dns virtual
    networks:
      - proxy-net

  v2raya:
    image: mirror-docker.runflare.com/mzz2017/v2raya:v2.2.7.5
    container_name: v2socks-v2raya
    logging: *default-logging
    restart: always
    network_mode: service:tun2proxy
    depends_on:
      - tun2proxy
    environment:
      - V2RAYA_LOG_FILE=/tmp/v2raya.log
      - V2RAYA_V2RAY_ASSETSDIR=/usr/local/share/v2ray
      - V2RAYA_V2RAY_BIN=/usr/local/bin/xray
      - V2RAYA_NFTABLES_SUPPORT=off
      - IPTABLES_MODE=legacy
    volumes:
      # - /lib/modules:/lib/modules:ro
      # - /etc/resolv.conf:/etc/resolv.conf
      - ./v2raya:/etc/v2raya

networks:
  proxy-net:
    driver: bridge
